### ISSUE TITLE
Set the weights of a single layer

### ISSUE THREAD

**Issue by leconteur** [aigamedev/scikit-neuralnetwork#106]
When using an imbalanced dataset, it is sometimes useful to set the biases of the softmax layer to the log of the class frequency. However, in the current implementation, we either have to set all the weights manually, or use the random initialization. Is it in the plan to make this feature available?

I know that it is possible to set the biases to the log values in pylearn2, but it could also be set by sknn.

**Comment by alexjc** [comment]
We don't have support for customization of the initialization yet, but it's a common feature we should support. Do you have any thoughts about the API?

**Comment by leconteur** [comment]
In pylearn2, there is the parameter in the constructor of the softmax layer:
```
 init_bias_target_marginals : dataset
        Take the probability distribution of the targets into account to
        intelligently initialize biases.
```

I do not have another use case, so I guess this would be relatively simple. I do not know if other backend support this, so maybe it could be done in sknn directly. As far as I know, this is relatively straightforward.
