### ISSUE TITLE
Ghost of 2.7 print strikes again

### ISSUE THREAD

**Issue by aflyax** [aigamedev/scikit-neuralnetwork#11]
(I am not sure if you guys know about this, but just in case...)

$ python examples/plot_mlp.py --params activation
Visualizing Parameters in a Modern Neural Network

Traceback (most recent call last):
  File "examples/plot_mlp.py", line 22, in <module>
    from sknn.mlp import MultiLayerPerceptronClassifier
  File "/home/alex/scikit-neuralnetwork/sknn/mlp.py", line 275
    print self.layers
             ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by alexjc** [comment]
Thanks @aflyax, the build caught it and emailed @ssamot:
https://travis-ci.org/aigamedev/scikit-neuralnetwork

I'm sure he'll fix it once he's back at the computer!


After the first release 0.1 we'll switch to branches and pull requests... :-)

**Comment by ssamot** [comment]
closed - late night coding....

**Comment by ssamot** [comment]
closed - late night coding....
