### ISSUE TITLE
Inspecting the trained model: show final weights

### ISSUE THREAD

**Issue by holderm** [aigamedev/scikit-neuralnetwork#116]
I'm new to scikit-neuronalnetwork, so this might be an easy question for one who is familiar with this libary.
For inspecting the model I would like to view the final weights of all layers.
So I want to use the functions called `get_weights()` in `mlp.py` or `get_biases()` for visualizing them.
Doing so I get
`AttributeError: 'Classifier' object has no attribute 'mlp'`
Can anyone suggests a solution?

**Comment by alexjc** [comment]
The easiest way to do this currently is to call `__getstate__` from the MLP.  Here's the implementation:
https://github.com/aigamedev/scikit-neuralnetwork/blob/master/sknn/mlp.py#L86

It will return a dictionary including tuples (weights, biases) in a long list.  This is the same function called during pickle.  We'll look at adding a more convenient accessor, though!

**Comment by pGit1** [comment]
When I do 

print classifier.__getstsate__ all I get returned are the hyperparamter settings after training. How exactly to get to the weights with __getstate__? Some example code would be awesome! Thanks!
