### ISSUE TITLE
Can we see the weights of the trained neural network? 

### ISSUE THREAD

**Issue by bridgesra** [aigamedev/scikit-neuralnetwork#118]
@alexjc Alex, is there a way to see the weights of the trained model? Especially for smaller models (1 hidden layer) i'd like to plot a histogram of the weights to see what features are contributing the most. 

thanks!

**Comment by alexjc** [comment]
See #116.

**Comment by bridgesra** [comment]
Thanks!

**Comment by alexjc** [comment]
Closed by 42397ef.
