### ISSUE TITLE
Manually set the weights of a Layer

### ISSUE THREAD

**Issue by timothyjlaurent** [aigamedev/scikit-neuralnetwork#119]
I would like to be able to manually set weights of the pereptron (in addition to getting the weights but that is #116). If there is some way to do this, I'd be happy to write up a PR.

**Comment by alexjc** [comment]
There's currently no way to do this, but I'd like to expose it as `get_parameters` and `set_parameters` somehow in the next release. As an intermediate measure, you can use inspiration from `__getstate__` and `__setstate__` and basically pretend to be pickling.

If you think you can do it, go for it! The only big decision is what data-structure to pass around in getter and setter... A list of tuples of numpy arrays?

**Comment by timothyjlaurent** [comment]
I will be taking a stab at this this week... I won't be handling anything fancy (eg convolution layers) - will let you know how it goes.
