### ISSUE TITLE
Manually train a NN

### ISSUE THREAD

**Issue by timothyjlaurent** [aigamedev/scikit-neuralnetwork#120]
I'd like to be able to add additional training iterations to a trained model.

**Comment by alexjc** [comment]
I'm not sure, but there was a time where you could just call `fit()` multiple times as necessary. How do you imagine the API for this?

**Comment by timothyjlaurent** [comment]
I'll check to see if this still works -- so I assume it would use the num iterations as a parameter to see how to many updates to do before returning?

**Comment by alexjc** [comment]
Yes, exactly.

**Comment by alexjc** [comment]
Calling fit multiple times works. Now there are also callbacks you can use to access the neural network during training. You can also `get_parameters` and `set_parameters` to do everything yourself.
