### ISSUE TITLE
I would like to be able to use a custom function for updating weights

### ISSUE THREAD

**Issue by timothyjlaurent** [aigamedev/scikit-neuralnetwork#121]
Although back propagation is great, it would be nice to be able to use other algorithms for updating weights.

**Comment by alexjc** [comment]
Yes, I started using LBFGS myself too. Wouldn't your #119 issue cover this?

**Comment by timothyjlaurent** [comment]
Yes it would in a manual way. With this I was thinking about how nice it would be to be able to use a function as a parameter but then I guess we would have to know more about the api (how weights are being passed around, etc.) before you would be able to design a function to update it.

**Comment by alexjc** [comment]
Leaving this request open to see if there's general interest. If enough people reply I can look into it!

**Comment by alexjc** [comment]
Using `set_parameters()` should do the trick! You can either do this yourself via your own training loop or use the new callbacks from v0.5.
