### ISSUE TITLE
Is there a way for assigning different weights for each sample or class?

### ISSUE THREAD

**Issue by juliuswang0728** [aigamedev/scikit-neuralnetwork#125]
I'm dealing with multi-class classification problem with scikit-neuralnetwork, and apparently there is some class imbalance problem. So, is it possible to customize the cost function by assigning different weights for each class? Thanks.

**Comment by alexjc** [comment]
No, not in the classification API. Maybe you could convert it yourself into a regression problem? Alternatively, duplicate the data for the less frequent example classes.

**Comment by alexjc** [comment]
I looked into this and I couldn't yet get it to work, but it should be possible. I'll pursue this if there's enough interest here!

**Comment by alexjc** [comment]
My experiments in [5ae453e] ran, but it didn't work as expected. I can't seem to disable (weight 0.0) certain training classes in MNIST and favor others.

Not sure what the problem is, any advice welcome.
