### ISSUE TITLE
Switch Away from PyLearn2

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#126]
A lot has happened in the 6 months since this project started. In particular, PyLearn2 that was among the leading libraries is now becoming un-maintained:
https://www.reddit.com/r/MachineLearning/comments/3spulp/pylearn2_is_no_longer_developed/

New features are rare and other libraries are pulling ahead on features. Also, fixing outstanding bugs in the convolution turned out to be very tough.

Going forward, we'll probably switch to another backend (thanks to the work already in place) and this is likely going to be `Lasagne` first. In the next release, PyLearn2 will be deprecated and then subsequently removed.

**Comment by pGit1** [comment]
Go with Blocks instead?

**Comment by alexjc** [comment]
Blocks is an option but I don't know it at all, been using Lasagne recently and was very impressed. Backend is underway for Lasagne (functional, but some tests fail). If you want to contribute Blocks it's becoming easier to insert new backends!

**Comment by alexjc** [comment]
Shipped in a5d63d9a9bb20783bf290aacc185c59bfd3b61db.
