### ISSUE TITLE
The class `sknn.mlp.Classifier` has no attribute `classes_`, making predicted probability hard to be corresponded to actual class.

### ISSUE THREAD

**Issue by xyguo** [aigamedev/scikit-neuralnetwork#130]
When I use a `sknn.mlp.Classifier` object to do classification, I use `predict_proba` to output confidence of each predicted class. But since the classifier has no attribute `classes_` (which is different to that of `sklearn`)  I can't find the corresponding classes of the predicted probabilities.

I've inspected the source code and noticed that you are using a `LabelBinarizer` to save actual class labels. I think it's tricky to extract class labels from that. Would you add a `classes_` attribute to it?

Thank you!

**Comment by alexjc** [comment]
I see, thanks for reporting... Try this for now:
> clf.label_binarizers[0]._classes

If you have multiple output classes, then you'll need to go through the list of label binarizers.
