### ISSUE TITLE
Prediction does not support sparse matrix

### ISSUE THREAD

**Issue by nxgtr** [aigamedev/scikit-neuralnetwork#139]
I am using sparse matrix (CSR matrix) to train high dimensional data, everything works perfect.

However, as it is expected, the test-set follows similar characteristics, then it is high dimensional as well. Prediction requires dense matrix, which results in MemoryError.

The relevant code seems to be at: https://github.com/aigamedev/scikit-neuralnetwork/blob/master/sknn/mlp.py#L255

Although I am not so sure as it seems odd that training supports sparse but predict does not.

Right now I just split the test set in chunks to bypass the issue.

**Comment by alexjc** [comment]
OK, great. Definitely a bug :-) If you remove the line you linked, does it still cause problems?

**Comment by alexjc** [comment]
It should work now with the master branch. To ship on PIP in the next release.
