### ISSUE TITLE
Mismatch between dataset size and units in output layer

### ISSUE THREAD

**Issue by darkz0ne** [aigamedev/scikit-neuralnetwork#140]
Hey this is not a dev request or a bug. Sorry about asking this question here, but i couldn't find any other forum.

nn=Classifier(layers=[Layer("Sigmoid",units=2),Layer("Sigmoid",units=2),Layer("Sigmoid",units=1)],n_iter=100)
X=np.array([[1,0],[0,0],[0,1],[1,1]])
y=np.array([[1],[0],[1],[0]])
nn.fit(X,y)

this gives me a mismatch error. but my arrays are according to format stated in the docs. (sample,features). any idea why this is happening?

**Comment by alexjc** [comment]
Could you report what the error was so people can find this in the future?

**Comment by darkz0ne** [comment]
It says "AssertionError: Mismatch between dataset size and units in the output layer".
I have one output unit and the y array is (4,1) in dimensions as specified in the docs (n_samples, output_vector).

**Comment by alexjc** [comment]
I see. Thanks for posting back!
