### ISSUE TITLE
Question: Regularize at the MLP Level

### ISSUE THREAD

**Issue by BrianMiner** [aigamedev/scikit-neuralnetwork#141]
What does it mean to have dropout at the MLP level (via regularize = 'dropout') versus the layer level? I understand L1 or L2 (with accompanying 'weight_decay') at the mlp level but not dropout. Is this applied to every layer if set at the mlp level?

**Comment by alexjc** [comment]
dropout_rate at the MLP level applies that dropout value to all layers, except if it has been overridden within a layer. It's the same as L2, weight_decay is applied everywhere except if overridden with the layer configuration.

**Comment by BrianMiner** [comment]
I was under the impression that L2 was only applied to the final weights (affected the loss function) I did not realize it was applied layer by layer.

**Comment by BrianMiner** [comment]
Is it possible to only apply L2 or L1 to the final weights? It looks like there is no option to differentiate L1 and L2 at the final layer (if that would be a way to accomplish this),   as only the weight_decay parameter is settable.

**Comment by alexjc** [comment]
If you set the weight_decay on the entire network to 0.0, then set weight_decay on the layers to what you need, that should work.  You can't mix L2 and L1.

If you want such advanced features you may need a lower-level library like Lasagne.
