### ISSUE TITLE
Does Classifier.fit actually takes weights?

### ISSUE THREAD

**Issue by moldot** [aigamedev/scikit-neuralnetwork#144]
The documentation says that Classifier.fit takes 'w' as its third parameter. I don't see the 'w' parameter when looking at help(Classifier) or help on an instance of Classifier. An error was thrown when I tried passing a third parameter.

**Comment by alexjc** [comment]
(Reposting comment from #135.)

We haven't yet pushed fit() with weight to PIP. It's in master only.

There's a different documentation page for stable (linked from PIP) here:
http://scikit-neuralnetwork.readthedocs.org/en/stable/guide_beginners.html

**Comment by paullo0106** [comment]
Cool, I look forward to using that feature on upgraded version very soon!

**Comment by alexjc** [comment]
We're waiting for Theano to make a release that supports all the convolution features we use via Lasagne, then it will ship. (Otherwise it's harder to assure the right libraries on each machine without shipping them ourselves like we did with PyLearn2.)

**Comment by alexjc** [comment]
New release is on PIP.

**Comment by paullo0106** [comment]
Great! Can't wait to use it
