### ISSUE TITLE
Quick question: is there any way to run classifier in multi-core?

### ISSUE THREAD

**Issue by lihang00** [aigamedev/scikit-neuralnetwork#147]
I think I saw a parameters before? But I can't find it in doc now...Could you guys point it out?
And is there any contact info I can get? Then I don't need open an issue, I can just mail to you guys and get my answer.

**Comment by alexjc** [comment]
It's best to open issues so the information is public. I don't really check email anymore, and when I do it's not for tech. support :-)

You can specify whether to use GPU or CPU:
http://scikit-neuralnetwork.readthedocs.org/en/latest/guide_intermediate.html#cpu-vs-gpu-platform

And you can run multiple jobs in parallel with `n_jobs`:
http://scikit-neuralnetwork.readthedocs.org/en/latest/guide_advanced.html#grid-search

I don't know if there's a way to run Theano on multiple CPUs. Get a good GPU and it'll be much faster (e.g. Amazon EC2).

**Comment by alexjc** [comment]
Try setting this environment variable and configuring flags on line 28 of `__init__.py`:
http://deeplearning.net/software/theano/tutorial/multi_cores.html#parallel-element-wise-ops-with-openmp

**Comment by alexjc** [comment]
Addressed by #165.
