### ISSUE TITLE
the autoencoder initialization bug

### ISSUE THREAD

**Issue by fayeshine** [aigamedev/scikit-neuralnetwork#152]
when run 

from sknn import ae
ae = ae.AutoEncoder(
        layers=[
            ae.Layer("Tanh", units=10),
            ae.Layer("Sigmoid", units=10)],
        learning_rate=0.002,
        n_iter=10,
        verbose=1)

it gives:

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-6dbd18bb2a75> in <module>()
      5         learning_rate=0.002,
      6         n_iter=10,
----> 7         verbose=1)

/home/wenjian/anaconda2/lib/python2.7/site-packages/sknn/nn.pyc in __init__(self, layers, warning, weights, random_state, learning_rule, learning_rate, learning_momentum, regularize, weight_decay, dropout_rate, batch_size, n_iter, n_stable, f_stable, valid_set, valid_size, loss_type, callback, debug, verbose, **params)
    469         self._backend = None
    470         self._create_logger()
--> 471         self._setup()
    472 
    473     def _setup(self):

/home/wenjian/anaconda2/lib/python2.7/site-packages/sknn/ae.pyc in _setup(self)
     99 
    100         backend.setup()
--> 101         self._backend = backend.AutoEncoderBackend(self)
    102 
    103     def fit(self, X):

/home/wenjian/anaconda2/lib/python2.7/site-packages/sknn/backend/__init__.pyc in __init__(self, _)
     16 class AutoEncoderBackend(object):
     17     def __init__(self, _):
---> 18         raise NotImplementedError("No backend sub-module imported.")
     19 
     20 

NotImplementedError: No backend sub-module imported.

**Comment by alexjc** [comment]
It's not a bug, it's not implemented. The PyLearn2 code was always questionable and we haven't yet ported the interface to the new Lasagne backend. See https://github.com/aigamedev/scikit-neuralnetwork/issues/129.
