### ISSUE TITLE
Still cant get to the weights of a Trained network

### ISSUE THREAD

**Issue by pGit1** [aigamedev/scikit-neuralnetwork#153]
I have a trained classifier and when I want to access the weights I get the error:

AttributeError: 'Classifier' object has no attribute 'get_parameters'

My classifier's name is fin_net. So why does fin_net.get_parameters not work!!? I love this library so much I just hate how hard a time I am having with getting to my weight matrices! :(

**Comment by alexjc** [comment]
You're using the version from Git master?

**Comment by pGit1** [comment]
My version says scikit-neuralnetwork 0.4. I simply did pip install
scikt-neuralnetwork to get the latest version.

**Comment by alexjc** [comment]
Ah, just get from master in the meantime! Once our dependencies ship new versions we can release easier...

**Comment by pGit1** [comment]
Alex how do I get it from the Git Master?

**Comment by alexjc** [comment]
Install like any other Python package. Details on front page.

**Comment by pGit1** [comment]
Nevermind! I figured it out using the git+ command followed by the url. I can see it works perfectly now. I just went with the original pip install because it said recommended. Is it always better to install from master branches?

**Comment by pGit1** [comment]
Thanks Alex! This library is awesome!
