### ISSUE TITLE
use with sklearn voting classifier

### ISSUE THREAD

**Issue by hasakura511** [aigamedev/scikit-neuralnetwork#154]
It gives me the following error when i predict after fitting. thanks. 

ValueError: could not broadcast input array from shape (1051,1) into shape (1051)

**Comment by alexjc** [comment]
As always with bug reports, good information is not just useful but required. Full callstack?

**Comment by hasakura511** [comment]
Yes, sorry about that. I put the MLPC in the voting classifier (sklearn)
like so..

        [ ("Voting", VotingClassifier(estimators=[\
             ("GNBayes",GaussianNB()),\
             ("MLPC", Classifier([Layer("Sigmoid", units=150),
Layer("Softmax")],learning_rate=0.001, n_iter=25, verbose=True)),\
]

I fit it, then run predict

    y_pred_is m[1].predict(X_train)

  File
"/home/hidemi/anaconda/lib/python2.7/site-packages/sklearn/ensemble/voting_classifier.py",
line 149, in predict
    predictions = self._predict(X)

  File
"/home/hidemi/anaconda/lib/python2.7/site-packages/sklearn/ensemble/voting_classifier.py",
line 226, in _predict
    return np.asarray([clf.predict(X) for clf in self.estimators_]).T

  File
"/home/hidemi/anaconda/lib/python2.7/site-packages/numpy/core/numeric.py",
line 474, in asarray
    return array(a, dtype, copy=False, order=order)

ValueError: could not broadcast input array from shape (1051,1) into shape
(1051)

Thank you for your support.

**Comment by alexjc** [comment]
The classifier needs to return a flattened array without the last dimension. Should be an easy PR if someone wants to try! Make sure all the other tests still pass. :-)

**Comment by fayeshine** [comment]
#159 @alexjc Tested on my machine, all function works

**Comment by alexjc** [comment]
I can't reproduce this with the latest scikit-learn. What version are you using?

**Comment by alexjc** [comment]
#164 seems to show it works with the latest sklearn. Can you provide more information?

**Comment by hasakura511** [comment]
it seems to be working now.  Thanks, and happy new year!
