### ISSUE TITLE
What us the "ExpLin" activation function? Any literature?

### ISSUE THREAD

**Issue by pGit1** [aigamedev/scikit-neuralnetwork#155]
Wondering where to find some literature on this...

**Comment by pGit1** [comment]
Never Mind. Found it....

**Comment by kostrykin** [comment]
@pGit1 Didn't it come on your mind to *share* whatever you had found?

**Comment by alexjc** [comment]
http://arxiv.org/abs/1511.07289

**Comment by pGit1** [comment]
Oh sorry my bad! :D Check it out: http://arxiv.org/abs/1511.07289
