### ISSUE TITLE
Lasagne backend doesn't iterate over all data when you set batch_size

### ISSUE THREAD

**Issue by jmgore75** [aigamedev/scikit-neuralnetwork#158]
In pull request #157 I describe how when you use a batch size, the lasagne backend does not train with all of the data, only blocks of that batch size (leaving out the bit at the end).  Also, if batch_size is greater than the total data size, it won't iterate over any data at all and will die with a zero division error.

**Comment by alexjc** [comment]
Yep, thanks for pointing it out. Just needs one test to make sure we catch such problems in the future.

**Comment by alexjc** [comment]
If you want me to merge this from your PR, please include the three tests from [7831214]. Thanks again!
