### ISSUE TITLE
Is scikit has NARX interface？Thankyou

### ISSUE THREAD

**Issue by wanghai1988** [aigamedev/scikit-neuralnetwork#162]

**Comment by alexjc** [comment]
Closing. Add more details please.

**Comment by wanghai1988** [comment]
Sorry, I said is too vague, I mean the NARX(nonlinear autoregressive model with exogenous inputs) model which use to process time series data processing

在 2015-12-31 18:32:45，"Alex J. Champandard" <notifications@github.com> 写道：


Closing. Add more details please.

**Comment by wanghai1988** [comment]
Sorry, I said is too vague, I mean the NARX(nonlinear autoregressive model with exogenous inputs) model which use to process time series data processing

**Comment by alexjc** [comment]
I don't know the algorithm, and if there's an implementation available in Lasagne/Theano. If there's enough demand, we could look into it.

**Comment by wanghai1988** [comment]
Thank you for the answer
