### ISSUE TITLE
GPU run doesn't work

### ISSUE THREAD

**Issue by nijuyoumo** [aigamedev/scikit-neuralnetwork#163]
When I used GPU to train the NN, it was running forever.
But when I used CPU it was only running about 40 min.
Thanks a lot.

**Comment by alexjc** [comment]
Not enough information. I'm closing this until you can file a bug report that we can work with.

http://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/

**Comment by nijuyoumo** [comment]
The program didn't stop and I got nothing. So I have no bug report. I only add like follow on the top:
from sknn.platform import gpu32

**Comment by alexjc** [comment]
What script did you use? What happened on CTRL+C? No output at all?
