### ISSUE TITLE
Support custom Layer types known by backend

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#179]
If a user specifies a Layer in the constructor that's known to the backend (lasagne) simply pass it through directly. This makes it possible to do more advanced architectures without "hitting the ceiling", at the cost of intuitiveness and simplicity.

**Comment by nikcheerla** [comment]
This would really be useful! The only reason I don't use scikit-neuralnetwork for all deep learning tasks right now is the fact that I can't easily add things like max-pooling layers or dropout layers.

**Comment by alexjc** [comment]
@nikcheerla The code is there, you can do things like:

```
layers=[Native(lasagne.layers.recurrent.LSTMLayer, <parameters>)]
```

Section in the documentation will follow soon.
