### ISSUE TITLE
Wrong .predict_proba() output shape for Classifier?

### ISSUE THREAD

**Issue by ralston3** [aigamedev/scikit-neuralnetwork#182]
I'm trying the `.predict_proba()` method on a multi-label problem. And while the method returns the appropriate values, instead of returning them as `[n_samples, n_classes]` it returns them as `[n_samples, n_probabilities]` 

Here is the output from a sample from a simple multi-label problem with 4 unique classes:

`[[0.50014246  0.49985754  0.50011709  0.49988291  0.50063539  0.49936461
   0.49984055  0.50015945]
     [0.50018613  0.49981387  0.50015697  0.49984303  0.50078478  0.49921522
   0.49983006  0.50016994]]`

While the values in each single array are correct, they aren't paired (e.g., `[0.5001, 0.4998], [0.5001, 0.4998]`), which would then make the size `[n_samples, n_classes]`. Was this intended? I apologize for any confusion.

-ralston3

**Comment by alexjc** [comment]
Thanks, it's a good question. I think you're right, returning sub-arrays would be more intuitive.

The most important decision factor is preserving compatibility with other sklearn classifiers and the rest of the functionality. Do you know how those work and what format they output? Are there other functions (e.g. `grid_search`) that would break if we changed the output?

**Comment by ralston3** [comment]
alexjc,

Many (if not all) sklearn classifiers (unless there's a real niche one that I'm forgetting about), output `.predict_proba()` with sub-arrays. `grid_search` itself actually outputs sub-arrays as well. So I think you'd be okay to do the same (it would also make things much more consistent with scikit).

In regards to your edit:  the `.predict_proba()` output for the same type of simple problem I mentioned above, using a `ensemble.RandomForestClassifier()` outputs: 

`[array([[ 0.5,  0.5],
        [ 0.7,  0.3]]), 
 array([[ 0.4,  0.6],
        [ 0.5,  0.5]]), 
 array([[ 0.7,  0.3],
        [ 0.7,  0.3]]), 
 array([[ 0.7,  0.3],
        [ 0.6,  0.4]])]
`

a list of `n outputs` (4 since the toy problem contains 4 unique classes) by `n_classes ` (classes being 2 [1 or 0 since an instance either belongs to a class or doesn't]).

While in the case of the `sknn.Classifier`, `.predict_proba()` for that same problem would output:

`[[0.50014246 0.49985754 0.50011709 0.49988291 0.50063539 0.49936461 0.49984055 0.50015945] [0.50018613 0.49981387 0.50015697 0.49984303 0.50078478 0.49921522 0.49983006 0.50016994]]`
<em>(I actually used dummy numbers but the shapes are the exact same as the output)</em>

So with the `ensemble.RandomForestClassifier()` output I can read that theres a 50/50 chance that the first test instance belongs to class 1. I can also tell that there is a 70/30 chance that the second test instance belongs to class1. Further, I can see that there's a 40/60 chance that the first test instance belongs to class 2...and so on and so forth. 

With the `sknn.Classifier` output it's just a bit confusing as to what I'm reading since the probabilities aren't in sub-arrays.

If that's what you guys intended then I apologizes for this hella long post, but I just wanted to make sure before I put it in the toolbox. The whole multi-label probability thing is definitely a brain twister.

**Comment by alexjc** [comment]
That sounds reasonable. It was an array because that's how it comes out of the underlying Regressor. Converting it into a list of arrays would work and solves the problem of having different class numbers per output index.

It shouldn't be too much work. If you want to tackle it you're welcome to!
