### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by DKaravolos** [aigamedev/scikit-neuralnetwork#199]
Hi Alex,

I would like to use your awesome neural network toolkit, but it seems that I cannot install it on Windows. 
I am using PyCharm with the latest Anaconda (4.0.0) and SciPy 0.17, but when I try to install the package, it wants to update SciPy (even though I already have 0.17) and I get the error that it cannot find Lapack and Atlas libraries. I checked the websites of those libraries, but it seems quite a hassle to install those libraries in windows. Do you have an idea how to fix that? Or is there another way to use your package in Windows?

Kind regards,
Daniel

**Comment by alexjc** [comment]
Try removing scipy from setup.py when you install?

**Comment by DKaravolos** [comment]
Thanks! I had not yet considered a manual installation. It worked. Now I have trouble running Theano. But it seems to be a common problem, which can be fixed (though installing Linux might be the best solution).
