### ISSUE TITLE
n_stable not work?

### ISSUE THREAD

**Issue by adywp** [aigamedev/scikit-neuralnetwork#206]
Hi,
I set n_stable = 5 and leave f_stable at default (0.001). Why these iterations below did not stop at the 6th epoch?

Epoch   |    Training Error   |    Validation Error   |    Time
-----------|------------------------|---------------------|----
    1     |     2.887e-03       |      4.975e-05    |     98.1s
    2     |     9.069e-07      |       4.949e-05    |     96.4s
    3     |     7.560e-07      |       4.942e-05    |     95.8s
    4     |     7.034e-07      |       4.938e-05    |    105.5s
    5     |     6.737e-07      |       4.936e-05    |    105.8s
    6     |     6.521e-07      |       4.934e-05    |    105.3s
    7     |     6.365e-07      |       4.933e-05    |    103.3s
    8     |     6.240e-07      |       4.931e-05    |    105.5s
    9     |     6.138e-07      |       4.930e-05    |    105.4s
   10    |      6.052e-07     |        4.930e-05   |     106.2s
   11    |      5.983e-07     |        4.929e-05   |     106.9s

and keep on going...
For further information, the Validation Error column was in green (while Training Error column was in blue). I noticed than in some cases they change colour to black.
What is the difference between green and black?

**Comment by alexjc** [comment]
If the validation error goes up, then a minima was reached, and the previous version is considered stable. If you want to terminate after 5 iterations use `n_iter=5`?
