### ISSUE TITLE
Investigate performance issues on GPU (slower) vs. CPU (faster)

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#26]
The benchmarks compared to `nolearn.lasagne` show that `sknn.mlp` performs relatively worse on the GPU (by about 20% or so), but on the CPU it's significantly better — sometimes over twice as fast!

Is this due to some misusage of PyLearn2?

**Comment by bmilde** [comment]
I skimmed over the code, but I really don't know pylearn2 too well. Some things to look into:

a) How are transfers handled? If the GPU memory size allows it, could the whole dataset be stored in GPU memory?
b) If data is transferred over and over again for each epoch, how are transfers split? Per Minibatch?
c) Are these transfers handled concurrently to the GPU computations on the last data batch (that would be ideal)

**Comment by alexjc** [comment]
Thanks. I can make some benchmarks to check for a).  For b) it falls into PyLearn2 mostly, but maybe we can control it with a parameter?  c) I've no idea about this yet, it may be as low-level as Theano.

@ssamot is our resident PyLearn2 guru, pinging him :-)

**Comment by alexjc** [comment]
It seems `lasagne` itself, at the core of the SGD, is slower.
````
Function profiling
==================
  Message: nolearn/lasagne.py:237
  Time in 18760 calls to Function.__call__: 3.404354e+01s
  Time in Function.fn.__call__: 3.358202e+01s (98.644%)
  Time in thunks: 2.837401e+01s (83.346%)
  Total compile time: 3.320012e-01s
    Number of Apply nodes: 38
    Theano Optimizer time: 2.954590e-01s
       Theano validate time: 9.655714e-03s
    Theano Linker time (includes C, CUDA code generation/compiling): 2.413487e-02s
       Import time 3.080845e-03s
````

Here is `pylearn2` for reference:
````
Function profiling
==================
  Message: sgd_update
  Time in 18760 calls to Function.__call__: 3.230413e+01s
  Time in Function.fn.__call__: 3.186233e+01s (98.632%)
  Time in thunks: 2.767399e+01s (85.667%)
  Total compile time: 3.671901e-01s
    Number of Apply nodes: 47
    Theano Optimizer time: 3.273101e-01s
       Theano validate time: 1.387763e-02s
    Theano Linker time (includes C, CUDA code generation/compiling): 2.715898e-02s
       Import time 3.425598e-03s
````

**Comment by alexjc** [comment]
Summary so far, the performance loss for `pylearn2` comes from Python outside of Theano.  Possibly copying/manipulating arrays inside the `train()` function.  It must be profiled with a regular Python profiler.
