### ISSUE TITLE
Packaging self-contained pylearn2 for the PyPI release?

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#28]
Since the goal of the project is to make deep neural networks and PyLearn2 more accessible, I'm wondering about packaging up the library along with the PyPI release of `sknn`.  It would be self-contained and `sknn` would load that up as a fallback...  What do you think?

It's not something that the PyLearn2 developers are considering right now (due to the overheads):
https://github.com/lisa-lab/pylearn2/issues/1493

... but could be worthwhile as part of this project.  We have some automated tests, and along with PyLearn2's test suite it can be pretty safe.

If there's already a PyLearn2 version installed then I think `sknn` should use that, maybe printing a debug message: "This is the packaged version of `sknn` but it's using a version of `pylearn2` that's already installed."

Thoughts welcome!

**Comment by stonebig** [comment]
Until `pylearn2` as a release exist on pypi, your suggestion seems the only meaningfull solution.

Ideal situation would be:
- pylearn2 exists as a wheel package with a perfectly predictable release commit,
- you don't need (then) to re-include pylearn2 in scikit-neuralnetwork wheel.

**Comment by ssamot** [comment]
I think I kind of agree with both comments above - packaging `PyLearn2` makes the use of the library transparent.

**Comment by alexjc** [comment]
OK, this seems to work, from the `wrap` branch.  Some links I found useful:
http://peterdowns.com/posts/first-time-with-pypi.html
https://tom-christie.github.io/articles/pypi/

**Comment by alexjc** [comment]
Assuming there's a symlink to the pylearn2 within `sknn`, release looks like this now:

````
python setup.py sdist
twine upload -r test dist/*.tar.gz
```

(This applies to testpypi.python.org.)
