### ISSUE TITLE
Support for greedy layer-wise pretraining

### ISSUE THREAD

**Issue by leconteur** [aigamedev/scikit-neuralnetwork#35]
I'm trying to build a deep-belief network. Is there a way to use a set of pretrained weights to initialize the parameters of the MLP? Is there plan to implement RBMs and autoencoders?

**Comment by alexjc** [comment]
I believe PyLearn2 supports auto-encoders, or would require minor additions to do so.  However, I believe those architectures are being deprecated in the code...

My biggest question is, what problem are you trying to solve?  Conventional wisdom for "modern" NN training is that you're probably better off doing supervised only, either with your own dataset or a related one if necessary.

**Comment by leconteur** [comment]
I am using an autoencoder because I only have a portion of my dataset which is labeled. I want to use the unlabeled portion of my dataset to do unsupervised training and then finetune using the labeled portion. 

Pylearn2 does support autoencoders and RBMs, however, since they are trained using the TransformerDataset, I am not sure how to do this in scikit-neuralnetwork.

**Comment by alexjc** [comment]
Ah, I see. Thanks for clarifying!

`sknn` so far wasn't implemented with this in mind, so I'm not sure how this would be integrated yet... I think we'll keep this feature back for after the 0.1 release, but if you have any more information/prototypes they'd be very welcome.

**Comment by leconteur** [comment]
Thank you for the quick answer. 

I think I will try to do a prototype. I will do a pull request if I have something.

**Comment by alexjc** [comment]
@leconter: Started looking into this... I presume the code will need to create a separate AutoEncoder model, train that, then extract the weights into a MLP model?

**Comment by leconteur** [comment]
That is what I have so far. Pylearn2 has a pretrained layer type in mlp. I created a separated class to train the autoencoder layers which returns the pretrained layer, and I use those layers in the mlp constructor. The only addition to the mlp class is to add a condition in the _create_layer method to call the pylearn2 pretrained layer constructor.

**Comment by alexjc** [comment]
@leconteur: I found your branch, did you commit those changes to it?

**Comment by leconteur** [comment]
Not yet, I have to clean up my code. I plan to do this next week.

**Comment by alexjc** [comment]
I can cope with messy code, ask @ssamot :-) Just let me know when you're ready!

**Comment by alexjc** [comment]
For reference: prototype by @leconter available as #50 and first-pass integration of just the auto-encoder in #52.

**Comment by alexjc** [comment]
OK, #52 has landed and going to prototype the pre-training code.

**Comment by alexjc** [comment]
Added new PR #58 that does weight transfer from the existing auto-encoder module.  See the PRETRAIN conditional in `bench_cifar10.py`.

@leconteur If you have any feedback about the API or functionality, let me know.

**Comment by alexjc** [comment]
To continue the discussion from the previous pull request, I'm not using the pylearn2 `PretrainedLayer` type because it doesn't play well with serialization, and neither of us wanted to sacrifice that core feature.

I think support for Rectifiers would be very welcome here, but it can be a separate PR.

**Comment by alexjc** [comment]
Closed by #58.
