### ISSUE TITLE
MAE as well as MSE

### ISSUE THREAD

**Issue by raddy** [aigamedev/scikit-neuralnetwork#36]
I believe this is a simple boolean flag in Pylearn's MLP so it should be pretty easy to include?

**Comment by alexjc** [comment]
Thanks, I will take a look later!

If you know what the flag is called or have any more information in the meantime, feel free to post it... Pull requests also welcome :-)

**Comment by raddy** [comment]
Yeah -- Sorry didn't mean to sound flip, I'm in Shanghai with pretty spotty internet and an employer not a fan of me doing anything OS haha.  I love the start on this library. Custom loss functions would be the grail for me but they'd require a pretty heavy amount of pylearn2 style code generation. 

The flag is "use_abs_loss" in Linear layer.

**Comment by alexjc** [comment]
What do you mean, heavy code generation?  It doesn't sound like hard work from your description...

**Comment by raddy** [comment]
I had thought to swap cost function would require building a Cost and a wrapping Model object?

**Comment by alexjc** [comment]
@raddy Try out the `loss` branch. Code is there, basic coverage tests seem to pass.

**Comment by raddy** [comment]
Sweet -- I'll play with this tomorrow. Very exciting!
