### ISSUE TITLE
logging error occurred with the given example code

### ISSUE THREAD

**Issue by erogol** [aigamedev/scikit-neuralnetwork#40]
import logging

log = logging.getLogger('sknn')
log.basicConfig(
        format="%(message)s",
        level=logging.DEBUG,
        stream=sys.stdout)

raises this error

AttributeError                            Traceback (most recent call last)
<ipython-input-5-3479a4503af4> in <module>()
      2 
      3 log = logging.getLogger('sknn')
----> 4 log.basicConfig(
      5         format="%(message)s",
      6         level=logging.DEBUG,

AttributeError: 'Logger' object has no attribute 'basicConfig'

**Comment by alexjc** [comment]
Thanks for reporting it! What version of Python?

**Comment by alexjc** [comment]
Ah, it's the documentation.

Just do:
````
import logging
logging.basicConfig(*params)
````

It'll be fixed shortly.

**Comment by alexjc** [comment]
Closed by [e82cba8].

**Comment by erogol** [comment]
still I cannot get any output from the code even I trigger verbose = 1

**Comment by alexjc** [comment]
@erogol If you set verbose=1 in `bench_mnist.py`, do you see the output?
