### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by dansbecker** [aigamedev/scikit-neuralnetwork#45]
Shouldn't there be a requirements.txt?

Right now, I can install this package using pip and it doesn't recognize pylearn2 as a dependency.

**Comment by alexjc** [comment]
@dansbecker Did you close this ticket because it resolved itself?

`setup.py` includes the dependencies listed. On PIP it contains its own version of `PyLearn2`.

**Comment by dansbecker** [comment]
@alexjc I closed the ticket when I realized it contains its own version of PyLearn2.
