### ISSUE TITLE
Support all activation types as Hidden / Output layers

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#5]
Currently, hidden layers have only non-linear activations and output layers are linear.  This is the most sensible in practice, but the library should allow using any activation in any layer as necessary.

**Comment by alexjc** [comment]
@ssamot Is there anything technical preventing the non-linear layer types from being used as output, and likewise linear ones being used as hidden layers?

The way it's structured now makes a lot of sense though, maybe we should keep it for now... and see what users think after a while :-)

**Comment by ssamot** [comment]
For regression you will be binding your outputs  - don't think it's going to work that well. Not sure for example you can do negative numbers with rectifier outputs. Plus the idea is that you create representations. I wouldn't touch it for now.

**Comment by alexjc** [comment]
As discussed, going to implement this with [3027166] because there are some legitimate uses and it's probably more consistent this way...
