### ISSUE TITLE
Runtime Error with nesterov (Exception: NaN in hidden0_W)

### ISSUE THREAD

**Issue by BrianMiner** [aigamedev/scikit-neuralnetwork#51]
Fitting a simple mlp with learning_rule = nesterov returns an error consistently (with sgd there is no error). Not sure if this is enough information or not. 

/home/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:10: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame
/home/anaconda/lib/python2.7/site-packages/IPython/kernel/__main__.py:11: SettingWithCopyWarning: A value is trying to be set on a copy of a slice from a DataFrame

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-3db38602bc46> in <module>()
     35     nn = Classifier(layers=[Layer("Rectifier", units=100),Layer("Softmax", units =4)], learning_rate=0.01, n_iter=10, learning_rule = 'nesterov')
     36 
---> 37     nn.fit(train_X, train_y)
     38 
     39     p=nn.predict(test_X)

/home/anaconda/lib/python2.7/site-packages/scikit-neuralnetwork/sknn/mlp.py in fit(self, X, y)
    910         yp = self.label_binarizer.transform(y)
    911         # Now train based on a problem transformed into regression.
--> 912         return super(Classifier, self)._fit(X, yp, test=y)
    913 
    914     def partial_fit(self, X, y, classes=None):

/home/anaconda/lib/python2.7/site-packages/scikit-neuralnetwork/sknn/mlp.py in _fit(self, X, y, test)
    788         for i in itertools.count(1):
    789             start = time.time()
--> 790             self.trainer.train(dataset=self.ds)
    791 
    792             self.mlp.monitor.report_epoch()

/home/src/package/pylearn2/training_algorithms/sgd.py in train(self, dataset)
    468             value = param.get_value(borrow=True)
    469             if not isfinite(value):
--> 470                 raise RuntimeError("NaN in " + param.name)
    471 
    472     def continue_learning(self, model):

RuntimeError: NaN in hidden0_W

**Comment by alexjc** [comment]
Try dropping your learning rate down, by 10x or more. `NaN` happens with any learning rule if the gradient descent diverges.  If this is the problem I will add a better error message to explain this...

**Comment by BrianMiner** [comment]
That did it, dropping the learning rate to 0.001 worked. Thanks! (one additional note is that the docs list a parameter called 'dropout' but it appears to really be 'dropout_rate').

**Comment by alexjc** [comment]
If you use PIP, it's still `dropout` from version 0.1. `dropout_rate` is in the latest from source and not yet released.  I'll check the versioning of the documentation!  Thanks.

**Comment by alexjc** [comment]
About to merge a fix for this that explains the solution... Renamed the issue so it's easier to search/find.  Thanks for reporting it!
