### ISSUE TITLE
Compatibility with GridSearchCV

### ISSUE THREAD

**Issue by mblondel** [aigamedev/scikit-neuralnetwork#54]
I think the layer parameters can't be tuned by GridSearchCV from scikit-learn. Possible solutions:

- Support hierarchical parameters in GridSearchCV from scikit-learn (hard)
- Ship your own modified GridSearchCV
- Change your API

One idea would be to replace 
```python
nn = Classifier(
    layers=[
        Layer("Rectifier", units=100),
        Layer("Linear")],
    learning_rate=0.02,
    n_iter=10)
```
by
```python
nn = Classifier(
    layers=["rectifier", "linear"],
    n_units=[100, "default"],
    learning_rate=0.02,
    n_iter=10)
```
but I am not sure GridSearchCV supports array parameters either.

CC @amueller @ogrisel

**Comment by alexjc** [comment]
Not one to shy away from the hard problems and destroy beautiful APIs for little benefit, I implemented the first option.  Not only that, it's done already and there are tests :-)

````
nn = Classifier(layers=[L("Rectifier", units=123), L("Linear", units=456)])
````

Here both layers are implicitly named `hidden0` and `output1` but you can override this using the `name` parameter.  (See the documentation about `name`.)  Then, your GridSearch parameters would be as follows for example:

* ``hidden0__units`` to change the number of units in the layer.
* ``output1__type`` to change the activation function type.

There's a test in `test_sklearn.py` AFAIR, I will add a section in the User Guide based on this reply too.

Let me know!

**Comment by mblondel** [comment]
Your solution sounds great. 

Indeed, a model selection section in the user guide would be helpful.

**Comment by mblondel** [comment]
Any reason not to use layer1, layer2, ... as the default names?

**Comment by alexjc** [comment]
Historical reasons... Hmm, would you start from `0` index?

**Comment by alexjc** [comment]
New documentation, including an advanced section with GridSearch, is live from [8e4ab8dbc1]:
http://scikit-neuralnetwork.readthedocs.org/en/latest/guide_advanced.html#grid-search

**Comment by mblondel** [comment]
> Hmm, would you start from 0 index?

No strong opinion but one reason for starting from 0 would be to follow Python's indexing.

> New documentation, including an advanced section with GridSearch, is live from

Great, you may also want to give an example using RandomizedSearchCV (recommended when the number of combinations is very large).

**Comment by alexjc** [comment]
I think 0 is best, was just surprised by your example.  Will also add another example.

Thanks for the feedback so far. If there's anything else we can change to make it more sklearn-friendly then let me know!

**Comment by mblondel** [comment]
Sorry, my comment was not about the indexing per-se. What I meant is that I don't think you need to differentiate between hidden and output layers in the default names. I would just use `layer_%d` for both hidden layers and the output layer. Adding a suffix to the output layer name even though there's only one output layer felt a bit awkward.

**Comment by alexjc** [comment]
OK, I removed the index from the output layer and added another documentation section. @ssamot and I talked about renaming the layers by default, but will do this as a separate lower priority request later.

**Comment by amueller** [comment]
I feel a bit stupid asking, but why did the list of objects not work with GridSearchCV? Because it was hard to specify the parameter grid? Or did it not work at all?

**Comment by alexjc** [comment]
@amueller The common use-case is to modify specific parameters within a nested `Layer` object, rather than replace the whole `Layer`.  For example tweaking units or activation functions.  I think that's why scikit-learn supports double-underscore as the syntax for accessing nested objects, because it's a common use-case.

Does that answer your question?

**Comment by amueller** [comment]
Ok, so it is not "not working" but it is just a bit cumbersome to write
```python
parms = {'layers': [[Layer("Rectifier", units=n_hidden),
        Layer("Linear")] for n_hidden in [100, 200, 500]]}
```
The double-underscores are a somewhat different use-case, I think.

**Comment by mblondel** [comment]
I think I had never seen the double underscore notation for this use case. We usually use it when the object implement `set_params` is an estimator. But I guess why not if it's properly documented. This is indeed convenient to use.

**Comment by mblondel** [comment]
There is also the question of how to tune the number of layers itself.

**Comment by alexjc** [comment]
@amueller For the single parameter use case, it's fine, but it doesn't scale nicely:

````
import itertools
ACTS = ["Rectifier", "Sigmoid", "Tanh"]
UNITS = [10, 50, 100, 200]
parms = {'layers': [[
                   Layer(activ1, units=n_hidden1),
                   Layer(activ2, units=n_hidden2),
                   Layer("Linear")]
               for (activ1, n_hidden1, activ2, n_hidden2) in
               itertools.product(ACTS, UNITS, ACTS, UNITS)}
````

I don't understand what's different about double-underscore here.  Will it continue to work?
