### ISSUE TITLE
Re-organize documentation into sections reusable from README.rst, index.rst, ...

### ISSUE THREAD

**Issue by alexjc** [aigamedev/scikit-neuralnetwork#56]
There's a fair bit of duplication due to site-specific limitations (e.g. PYPI) but some sections could and should be included modularly.  Is it supported by GitHub?

**Comment by esafak** [comment]
[RST has an include directive, but it is not supported due to security issues](https://github.com/github/markup/issues/172)

**Comment by alexjc** [comment]
Thanks @esafak. Copy paste will have to do!
