### ISSUE TITLE
Issue with n_jobs and randomized search

### ISSUE THREAD

**Issue by BrianMiner** [aigamedev/scikit-neuralnetwork#64]
It seems that the package fails when using a pipeline with randomized search CV with more than a single parallel job. When n_jobs is set to -1 as below, the error returned is "AssertionError: The neural network has not been initialized." If this argument is removed, the code appears to run properly. 

```
clf_Pipeline = Pipeline([('tfidf_qtd', TfidfVectorizer(stop_words='english',tokenizer=PorterTokenizer())),
                         ('svd', TruncatedSVD()),
                          ('nn', Classifier(layers=[Layer(type="Rectifier"),Layer(type="Rectifier"),Layer("Softmax")],n_iter=25))])



parameters= { 'tfidf_qtd__min_df' : sp_randint(3,10),
             'tfidf_qtd__ngram_range' : [(1,3),(1,4),(1,5)],
             'svd__n_components': sp_randint(100,300),
             'nn__learning_rate':sp_rand(0.001,0.05),
             'nn__hidden0__units' : sp_randint(100,300),
             'nn__hidden1__units' : sp_randint(100,300)
            }


gscv= RandomizedSearchCV(estimator=clf_Pipeline,param_distributions=parameters,cv=3, verbose=1, scoring=kappa_scorer, n_iter=15, n_jobs=-1)

gscv.fit(trainX['qtd'],trainy)
```

**Comment by alexjc** [comment]
Thanks for the report. I've never used that `n_jobs` paramater! I'll try to dig into it a bit more next week. :-)

**Comment by alexjc** [comment]
Partly related, have you tried running the code on a CUDA-enabled GPU?  If so, I'm not sure if performance will increase with `n_jobs`, but I'd be curious to hear otherwise!

**Comment by BrianMiner** [comment]
Awesome thank you!

**Comment by alexjc** [comment]
Thanks for reporting, let me know if there's anything else that comes up. I haven't really stress tested multiple jobs!

**Comment by BrianMiner** [comment]
I tried to run a gridsearchcv and there is a warning about sknn not 
having a logger. Adding this:

importlogging
logging.basicConfig()

There is then the following warning - repeated once for each fit in the cv.

WARNING:sknn:Serializing a neural network that was not initialized

The program finishes fine (?) but thought Id let you know.
