### ISSUE TITLE
Logging using verbose = True, isn't working in mlp.Regressor

### ISSUE THREAD

**Issue by ansrivas** [aigamedev/scikit-neuralnetwork#97]
Hello team AIgamedevs, 
Logging is not working if I pass only "verbose = True" in mlp.Regressor, but if I import the global logger "log" and set the logging level to DEBUG/INFO , it works.

The function create_logger() returns , since the len(log.parent.handlers) evaluates to 1, but if I use this:

from sknn.mlp import Regressor, Layer, log, logging
log.setLevel(logging.DEBUG)

Then, I can see the debug logs.

**Comment by alexjc** [comment]
Did you do any other configuration of the logging before creating the mlp.Regressor, or use a library that does that for you?

**Comment by ansrivas** [comment]
It works actually, sorry for the confusion.  I had a couple of extra unused imports which were conflicting with the logging. 
Thanks for this wonderful library.

**Comment by alexjc** [comment]
OK, thanks for the report. Closing this issue!
